# Generated by Django 5.1.3 on 2024-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura_ola', models.FloatField(verbose_name='Altura de la ola (en metros)')),
                ('direccion_ola', models.CharField(max_length=50, verbose_name='Dirección de la ola (cardinal)')),
                ('periodo_ola', models.IntegerField(verbose_name='Periodo de la ola (en segundos)')),
                ('direccion_viento', models.CharField(max_length=50, verbose_name='Dirección del viento (cardinal)')),
                ('velocidad_viento', models.FloatField(verbose_name='Velocidad del viento (en km/h)')),
                ('coeficiente_marea', models.IntegerField(verbose_name='Coeficiente de marea')),
                ('situacion_geografica', models.CharField(max_length=255, verbose_name='Situación geográfica del lugar')),
                ('capturas', models.TextField(verbose_name='Capturas (tipo de especies)')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
